---
- hosts: all
  become: true
  gather_facts: false
  pre_tasks:
  - name: Install python3 for Ansible
    raw: bash -c "test -e /usr/bin/python3 || (apt -qqy update && apt install -qqy python3-minimal)"
    register: output
    changed_when: output.stdout != ""

- hosts: bind-master
  vars:
    colo: dnscfg
  roles:
  - bind
